kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerPort: 6443
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.localtest.me"]
    endpoint = ["http://localhost:31500"]
    
nodes:
- role: worker
  extraMounts:
  - hostPath: mounts
    containerPath: /var/local-path-provisioner/

- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:

  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 31500
    hostPort: 31500
    protocol: TCP
    listenAddress: "127.0.0.1"
  extraMounts:
  - hostPath: mounts/workers
    containerPath: /var/local-path-provisioner/
