apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  repo: https://helm.traefik.io/traefik
  chart: traefik
  targetNamespace: ingress
  valuesContent: |-
    replicas: 1
    deployment:
      enabled: true
      # Can be either Deployment or DaemonSet
      kind: Deployment
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.{{ domain }}`) 
        entryPoints: ["websecure"]
    experimental:
      plugins:
        enabled: true
    global:
      systemDefaultRegistry: ""
    nodeSelector:
      ingress-ready: "true"
    ingressClass:
      enabled: true
      isDefaultClass: true
    hostNetwork: true

    ports:
      traefik:
        expose: true
      websecure:
        tls:
          enabled: true
        port: 443
        hostPort: 443
        expose: true
        exposedPort: 443
    service:
      type: ClusterIP
    priorityClassName: system-cluster-critical
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    rbac:
      enabled: true
    tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
    logs:
      general:
        format: json
        level: DEBUG
      access:
        enabled: true
    tlsStore: 
      default:
        defaultCertificate:
          secretName: k8s-tls