
- name: Set facts
  set_fact:
    arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'ansible_architecture' }}"
    distribution: "{{ 'linux' if ansible_distribution in ['Ubuntu','Debian'] else 'darwin'}}"
    
- file: 
    path: "{{binaries_path}}"
    state: directory

- get_url:
    url: https://dl.filippo.io/mkcert/latest?for={{distribution}}/{{arch}}
    dest: "{{binaries_path}}/mkcert"
    mode: +x

- get_url:
    url: https://kind.sigs.k8s.io/dl/v0.18.0/kind-{{distribution}}-{{arch}}
    dest: "{{binaries_path}}/kind"
    mode: +x


- uri:
    url: https://github.com/helm/helm/releases
    follow_redirects: true
    return_content: yes
  register: helm_version

- get_url:
    url: "https://get.helm.sh/helm-{{(helm_version.content|regex_findall('/helm/helm/releases/tag/(v3.[0-9]*.[0-9]*)'))[0]}}-{{distribution}}-{{arch}}.tar.gz"
    dest: /tmp/helm.tar.gz

- command: tar -xvf  /tmp/helm.tar.gz -C {{binaries_path}}/ --strip-components 1 {{distribution}}-{{arch}}/helm
  args:
    creates: "{{binaries_path}}/helm"
    warn: false 
